version: '3.8'

services:
  backend:
    image: backend_gastos
    container_name: backend_gastos
    restart: always
    depends_on:
      - frontend
    env_file:
      - .env
    environment:
      - NODE_ENV=production # 🔹 Asegura que el backend use producción
    ports:
      - "8080:8080"
    networks:
      - red_gastos

  frontend:
    image: frontend_gastos
    container_name: frontend_gastos
    restart: always
    ports:
      - "80:80"
    networks:
      - red_gastos

networks:
  red_gastos:
