version: '3.8'

services:
  app:
    container_name: gastos_app
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - red_gastos
    volumes:
      - .:/app

  cronjob:
    container_name: gastos_cron
    build: .
    command: ["node", "cronjob/notificarVencimientos.js"]
    depends_on:
      - app
    networks:
      - red_gastos
    volumes:
      - .:/app

networks:
  red_gastos:
    external: false